### PR TITLE
Update Google Tag Manager snippet

### PR DESCRIPTION
**Pull request by contolini**
Per GHE/cfgov/platform/issues/390.

@Scotchester

### CODE REVIEW

**Comment by Scotchester** [comment]
The instructions said "as close to the opening `<head>` tag as possible". Should we move it above Modernizr?

**Comment by Scotchester** [comment]
Please update the version in `package.json`.

**Comment by contolini** [comment]
> The instructions said "as close to the opening <head> tag as possible". Should we move it above Modernizr?

Because modernizr is used for feature detection I didn't want to risk any FOUC-like side effects by putting scripts above it. I figure UX should come before analytics. I don't *think* GTM will be affected.

**Comment by Scotchester** [comment]
Agreed :+1:

**Comment by Scotchester** [comment]
After releasing this (I might need to do the npm release), you'll need to update this dependency in owning-a-home, fin-ed-resources, and know-before-you-owe to get the chance to propagate.

**Comment by contolini** [comment]
@Scotchester It looks like all three of those repos use [caret notation](https://github.cfpb.gov/CFGOV/know-before-you-owe/blob/master/package.json#L20) so they'll pull in the latest version of this repo. Is it just a matter of re-deploying them?

**Comment by Scotchester** [comment]
Yeah, I suppose in theory, that's true.

**Pull request merged**
