### PR TITLE
Baseurl and social share icons

### PR DESCRIPTION
**Pull request by danny8000**
Added baseurl functionality so micro-sites based on these templates can be served out of a sub-directory while preserving the ability to have "relative to site root" links to static assets.

Fixed bug in image src for social share urls

### CODE REVIEW

**Comment by Scotchester** [comment]
I remembered something that eliminates the need for `baseurl`! Check this out:

```html
<link rel="stylesheet" href="{{ url_for('static', filename='css/main.min.css') }}">
```

I don't entirely understand how it works. `url_for` is a Flask function that's exposed to Jinja. But I set up fin-ed-resources as shown above and it works great. Try it out in your project, and if it looks good, we might be able to forego the `baseurl` addition.

**Comment by danny8000** [comment]
Interesting idea, did you add this logic to the base sheer template, I don't see it here:

https://github.com/Scotchester/cfgov-sheer-templates/blob/clownfish/_layouts/base.html

**Comment by Scotchester** [comment]
I have not yet.

**Comment by Scotchester** [comment]
If it works for you, you can add it in this PR.

**Comment by danny8000** [comment]
I think it gets that url_for information from WSGI via Flask. So what happens if we move off of Jinga2 / Sheer / Flask / WSGI and onto Jinga2 / Django / WSGI ? I wonder if url_for would still work?

Also, does url_for work for you in your local development environment?

**Comment by Scotchester** [comment]
Good question. @rosskarchner, any ideas on that?

Yes, it does work for me locally.

**Comment by rosskarchner** [comment]
url_for('static'...)  is explicitly supported in django-sheerlike:

https://github.com/rosskarchner/django-sheerlike/blob/master/sheerlike/__init__.py#L20

A more Django-y way to accomplish the same things exists too.

**Comment by Scotchester** [comment]
Thanks, Ross!

**Comment by Scotchester** [comment]
Superseded by #6.

**Pull request closed without merging**
