### PR TITLE
Turn this into a Bower component and add Nemo shim stuff

### PR DESCRIPTION
**Pull request by Scotchester**
This PR has two main goals:
1. Update this repo so that it can be used as a Bower dependency.
2. Add teh codez necessary to use these in Sheer-powered sites that use the extant header and footer from the Nemo theme (as responserized by the owning-a-home team), which is necessary until Flapjack launches.

## Additions

- New base Sheer layouts and includes from cfgov-refresh
- Nemo shim header & footer templates, plus the necessary CSS & JS

## Removals

- Placeholder header and footer templates.
- Outdated share macro

## Testing

- [Add this branch as a dependency in `bower.json`](https://github.cfpb.gov/CFGOV/fin-ed-resources/blob/master/bower.json#L26) and run `bower install`
- Add [this `grunt copy` subtask](https://github.cfpb.gov/CFGOV/fin-ed-resources/blob/master/Gruntfile.js#L262-L275) and run `grunt copy:cfgov-sheer-templates`

## Review

- @ascott1 
- @contolini 
- @cfpb/front-end-team-admin 

## Preview

You can see it working live at http://www.consumerfinance.gov/adult-financial-education/

[Preview this PR without the whitespace changes](?w=0)

## Notes

- I'd like to get this to a point where all projects using Sheer for templating can use this as a common base, extending as necessary for their own purposes. If you see anything here that would stand in the way of that goal, let's chat about it!

### CODE REVIEW

**Comment by cfarm** [comment]
COOL!!
@virginiacc, we should use this on owning a home.

**Comment by ascott1** [comment]
:heart_eyes:

**Comment by ascott1** [comment]
This looks great @Scotchester. Most of it is adapted from other projects already in production. Giving it the :+1:

**Comment by Scotchester** [comment]
Thanks! @cfarm and @virginiacc, I can help you get it set up after next week.

**Pull request merged**
